version: '3.3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:${TRAEFIK_VERSION}
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.acme.acme.httpchallenge=true"
      - "--certificatesresolvers.acme.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.acme.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.acme.acme.storage=/letsencrypt/acme.json"
      # uncomment the lines below if you want to use a LetsEncrypt Staging issuer for testing
      # - "--certificatesresolvers.acme-staging.acme.httpchallenge=true"
      # - "--certificatesresolvers.acme-staging.acme.httpchallenge.entrypoint=web"
      # - "--certificatesresolvers.myresolver.acme-staging.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # - "--certificatesresolvers.acme-staging.acme.email=${ACME_EMAIL}"
      # - "--certificatesresolvers.acme.acme-staging.storage=/letsencrypt/acme-staging.json"
      # End of lines for LetsEncrypt Staging issuer
      - "--log.filePath=/logs/traefik.log"
      # Leave the next two lines alone if you want access logs, if not comment them.
      - "--accesslog=true"
      - "--accesslog.filepath=/logs/access.log"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Volume for certificate storage
      - /data/traefik/letsencrypt:/letsencrypt
      # Volume for logging
      - /data/traefik/logs:/logs

networks:
  default:
    name: traefik
    external: true
