# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Substitute secrets in file
        uses: jwsi/secret-parser@v1
        with:
          filename: traefik/docker-compose.yml
          secret-name: letsencrypt_email
          secret-value: ${{ secrets.letsencrypt_email }}

      - name: Deploy to Docker swarm
        uses: docker-deployment-action@v1
        with:
          remote_docker_host: root@conxtor.com
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose-v2
          copy_stack_file: false
          deploy_path: /root/traefik-deployment
          stack_file_name: traefik/docker-compose.yml
          keep_files: 5
          args: -p traefik
